### ISSUE TITLE
Floating point exception in dead oil model

### ISSUE THREAD

**Issue by FishYNY** [GEOSX/GEOS#2358]
I was trying to run a simulation using dead oil model (oil, gas, water) coupling with multiphasePoroelasticity model. But "Floating point exception" error came out.  Can geosx solve problems on three phase fluid flow coupling with mechanics in field scale now?

GEOSX version: 0.2.0 (develop, sha1: bbd1948c0)
  - c++ compiler: gcc 9.4.0
  - MPI version: Open MPI v4.0.3, package: Debian OpenMPI, ident: 4.0.3, repo rev: v4.0.3, Mar 03, 2020
  - HDF5 version: 1.12.1
  - Conduit version: 0.8.2
  - VTK version: 9.1.0
  - RAJA version: 2022.3.0
  - umpire version: 2022.3.0
  -  adiak version: ..
  - caliper version: 2.8.0
  - METIS version: 5.1.0
  - PARAMETIS version: 4.0.3
  - scotch version: 6.0.9
  - superlu_dist version: 6.3.0
  - suitesparse version: 5.7.9
  - hypre development version: v2.27.0-9-g52802b646 (master)
Adding Solver of type MultiphasePoromechanics, named multiphasePoroelasticity
Adding Solver of type SolidMechanicsLagrangianSSLE, named linearElasticity
Adding Solver of type CompositionalMultiphaseFVM, named compflow
Adding Mesh: InternalMesh, mesh
Adding Geometric Object: Box, source
Adding Geometric Object: Box, sink

Adding Geometric Object: Box, xneg
Adding Geometric Object: Box, xpos
Adding Geometric Object: Box, yneg
Adding Geometric Object: Box, ypos
Adding Geometric Object: Box, zneg
   TableFunction: B_o_table
   TableFunction: visc_o_table
   TableFunction: B_g_table
   TableFunction: visc_g_table
Adding Event: PeriodicEvent, vtkOutputs
Adding Event: PeriodicEvent, solverApplications1
Adding Event: PeriodicEvent, solverApplications2
Adding Event: PeriodicEvent, solverApplications3
Adding Event: PeriodicEvent, restarts
Adding Event: PeriodicEvent, linearElasticityStatistics
Adding Event: PeriodicEvent, solverApplications
Adding Event: SoloEvent, multiphasePoroelasticityPreEquilibrationStep
Adding Event: SoloEvent, solidMechanicsPreEquilibrationStep
Adding Event: PeriodicEvent, solverApplicationsEquilibration
Adding Event: SoloEvent, multiphasePoroelasticityPostEquilibrationStep
Adding Event: SoloEvent, solidMechanicsPostEquilibrationStep
Adding Event: PeriodicEvent, compflowStatistics
Adding Output: VTK, vtkOutput
Adding Output: Restart, restartOutput
Adding Object CellElementRegion named reservoir from ObjectManager::Catalog.
Adding Object CellElementRegion named top from ObjectManager::Catalog.
Adding Object CellElementRegion named bottom from ObjectManager::Catalog.
mesh: total number of nodes = 170586
mesh: total number of elems = 160000
regionQuadrature: meshBodyName, meshLevelName, regionName, subRegionName = mesh, Level0, bottom, bottom
mesh/Level0/bottom/bottom/fluid allocated 8 quadrature points
mesh/Level0/bottom/bottom/rock allocated 8 quadrature points
mesh/Level0/bottom/bottom/relperm allocated 8 quadrature points
regionQuadrature: meshBodyName, meshLevelName, regionName, subRegionName = mesh, Level0, reservoir, reservoir
mesh/Level0/reservoir/reservoir/fluid allocated 8 quadrature points
mesh/Level0/reservoir/reservoir/rock allocated 8 quadrature points
mesh/Level0/reservoir/reservoir/relperm allocated 8 quadrature points
regionQuadrature: meshBodyName, meshLevelName, regionName, subRegionName = mesh, Level0, top, top
mesh/Level0/top/top/fluid allocated 8 quadrature points
mesh/Level0/top/top/rock allocated 8 quadrature points
mesh/Level0/top/top/relperm allocated 8 quadrature points
mesh: importing field data from mesh dataset
Received signal 8: Floating point exception
Floating point exception:

** StackTrace of 13 frames **
Frame 0: /lib/x86_64-linux-gnu/libc.so.6 
Frame 1: geosx::constitutive::DeadOilFluid::KernelWrapper::compute(double, double, LvArray::ArraySlice<double const, 1, 0, int> const&, geosx::constitutive::MultiFluidVarSlice<double, 1, 0, 1>, geosx::constitutive::MultiFluidVarSlice<double, 1, 0, 1>, geosx::constitutive::MultiFluidVarSlice<double, 1, 0, 1>, geosx::constitutive::MultiFluidVarSlice<double, 1, 0, 1>, geosx::constitutive::MultiFluidVarSlice<double, 1, 0, 1>, geosx::constitutive::MultiFluidVarSlice<double, 1, 0, 1>, geosx::constitutive::MultiFluidVarSlice<double, 2, 1, 2>, geosx::constitutive::MultiFluidVarSlice<double, 0, -1, 0>) const 
Frame 2: geosx::CompositionalMultiphaseBase::updateFluidModel(geosx::ObjectManagerBase&) const 
Frame 3: /home/pku/codes/codes02232023/GEOSX/build-your-platform-release/lib/libgeosx_core.so 
Frame 4: geosx::CompositionalMultiphaseBase::initializeFluidState(geosx::MeshLevel&, LvArray::ArrayView<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, 1, 0, int, LvArray::ChaiBuffer> const&) 
Frame 5: /home/pku/codes/codes02232023/GEOSX/build-your-platform-release/lib/libgeosx_core.so 
Frame 6: geosx::CompositionalMultiphaseBase::initializePostInitialConditionsPreSubGroups() 
Frame 7: geosx::dataRepository::Group::initializePostInitialConditions() 
Frame 8: geosx::dataRepository::Group::initializePostInitialConditions() 
Frame 9: geosx::dataRepository::Group::initializePostInitialConditions() 
Frame 10: geosx::GeosxState::applyInitialConditions() 
Frame 11: main 
Frame 12: __libc_start_main 
Frame 13: _start 
=====

--------------------------------------------------------------------------
MPI_ABORT was invoked on rank 0 in communicator MPI_COMM_WORLD
with errorcode 1.

NOTE: invoking MPI_ABORT causes Open MPI to kill all MPI processes.
You may or may not see output from other processes, depending on
exactly when Open MPI kills them.

[mycase.zip](https://github.com/GEOSX/GEOS/files/11080205/mycase.zip)

**Comment by francoishamon** [comment]
Hi @FishYNY we will have a look. Could you please include the pvt files so we can reproduce the error?

**Comment by FishYNY** [comment]
Hello, @francoishamon Thanks a lot.
[vtkfiles.zip](https://github.com/GEOSX/GEOS/files/11082776/vtkfiles.zip)

**Comment by francoishamon** [comment]
Thanks!

If you run your example with a recent version of GEOS, you will see that your initial and boundary conditions are ignored:
```
***** LOCATION: /g/g90/hamon1/geosx/GEOS/src/coreComponents/fieldSpecification/FieldSpecificationManager.cpp:169
***** Controlling expression (should be false): true
***** Rank 0: 
reservoirinitialComposition_oil: there is/are no set(s) named `reservoir` under the objectPath `ElementRegions/reservoir`, check the XML input
```

To fix this, you need to change the set names that you have used:
```
   <FieldSpecification                                                                                                                                                                  
      name="reservoirinitialComposition_oil"                                                                                                                                             
      initialCondition="1"                                                                                                                                                               
      setNames="{ all }"                                                                                                                                                                 
      objectPath="ElementRegions/reservoir"                                                                                                                                              
      fieldName="globalCompFraction"                                                                                                                                                     
      component="0"                                                                                                                                                                      
      scale="0.8"/>                                                                                                                                                                      
    <FieldSpecification                                                                                                                                                                  
      name="reservoirinitialComposition_gas"                                                                                                                                             
      initialCondition="1"                                                                                                                                                               
      setNames="{ all }"                                                                                                                                                                 
      objectPath="ElementRegions/reservoir"                                                                                                                                              
      fieldName="globalCompFraction"                                                                                                                                                     
      component="1"                                                                                                                                                                      
      scale="0.001"/>                                                                                                                                                                    
    <FieldSpecification                                                                                                                                                                  
      name="reservoirinitialComposition_water"                                                                                                                                           
      initialCondition="1"                                                                                                                                                               
      setNames="{ all }"                                                                                                                                                                 
      objectPath="ElementRegions/reservoir"                                                                                                                                              
      fieldName="globalCompFraction"                                                                                                                                                     
      component="2"                                                                                                                                                                      
      scale="0.199"/>       
```

Also, unfortunately, there is one place in the XML input where the order of blocks matters: `Events`. So, I slightly reordered your events to make sure everything works well with the initialization.

[mycase_fixed.zip](https://github.com/GEOSX/GEOS/files/11083248/mycase_fixed.zip)

**Comment by FishYNY** [comment]
Thanks a lot!
