### ISSUE TITLE
Inconsistent behavior with varying number of ranks- floating point exception

### ISSUE THREAD

**Issue by RayEGU** [GEOSX/GEOS#2365]
Hello Everyone,
We’re trying to run a CO2 injection model in a tetrahedral grid with one well.

The model is run with:
- PANGEA-2 machine
- gcc 8.3.0 compiler
- the Geos version 250c547.

For the MPI ranks number n= 8, 14, 32 and 64, it works very well, but when we change to n=16,
we got this following error message:
![image](https://user-images.githubusercontent.com/127122510/228556048-22d446be-bb27-48be-b75f-72945183ef8a.png)
 
Here you’ll find the simulation folder :

[SimuA.zip](https://github.com/GEOSX/GEOS/files/11101421/SimuA.zip)

**Comment by francoishamon** [comment]
@RayEGU thanks very much for reporting this problem. You are right that the results should not depend that much on the number of ranks. I fixed a problem in the code which was causing the problem.

Now at the end of the simulation I am getting:

1 rank:
```
compflowStatistics, Reservoir: Phase mass: { 2.27271e+09, 4.85002e+10 } kg
```

16 ranks:
```
compflowStatistics, Reservoir: Phase mass: { 2.27271e+09, 4.85002e+10 } kg 
```

Also, on a different topic, I recommend you to use `targetPhaseVolFractionChangeInTimeStep="0.05"` in `CompositionalMultiphaseFVM` to have a less aggressive time stepping. Your simulation will be faster.

**Comment by RayEGU** [comment]
> @RayEGU thanks very much for reporting this problem. You are right that the results should not depend that much on the number of ranks. I fixed a problem in the code which was causing the problem.
> 
> Now at the end of the simulation I am getting:
> 
> 1 rank:
> 
> ```
> compflowStatistics, Reservoir: Phase mass: { 2.27271e+09, 4.85002e+10 } kg
> ```
> 
> 16 ranks:
> 
> ```
> compflowStatistics, Reservoir: Phase mass: { 2.27271e+09, 4.85002e+10 } kg 
> ```
> 
> Also, on a different topic, I recommend you to use `targetPhaseVolFractionChangeInTimeStep="0.05"` in `CompositionalMultiphaseFVM` to have a less aggressive time stepping. Your simulation will be faster.

Thanks a lot @francoishamon , I tested it with your Geos version 2e19665 and your suggestions,
 it worked very well 😊.
